import {LandingPage} from "../../../components/landing-page";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <LandingPage />
  );
};

export default page;
